#!/usr/bin/env bash
# MALINFO Quick Deployment Script
# Usage: ./deploy.sh [railway|render|fly|selfhosted] [domain] [admin-email] [admin-password]
#
# Examples:
#   ./deploy.sh selfhosted malinfo.myagency.gov admin@myagency.gov "SecurePass123!"
#   ./deploy.sh fly malinfo.myagency.gov
#   ./deploy.sh railway malinfo.myagency.gov

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$PROJECT_ROOT"

PLATFORM="${1:-selfhosted}"
DOMAIN="${2:-malinfo.local}"
ADMIN_EMAIL="${3:-}"
ADMIN_PASSWORD="${4:-}"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }
log_step() { echo -e "${BLUE}[STEP]${NC} $1"; }

# ─────────────────────────────────────────────────────────────────────────────
# INTERACTIVE SETUP (if admin credentials not provided)
# ─────────────────────────────────────────────────────────────────────────────

prompt_admin_credentials() {
    if [[ -z "$ADMIN_EMAIL" ]]; then
        echo ""
        log_step "Initial Admin Account Setup"
        echo "This account will have full administrative access to MALINFO."
        read -rp "Admin email: " ADMIN_EMAIL
        if [[ -z "$ADMIN_EMAIL" ]]; then
            log_error "Admin email is required"
            exit 1
        fi
    fi
    
    if [[ -z "$ADMIN_PASSWORD" ]]; then
        read -rsp "Admin password (min 12 chars): " ADMIN_PASSWORD
        echo ""
        if [[ ${#ADMIN_PASSWORD} -lt 12 ]]; then
            log_error "Password must be at least 12 characters"
            exit 1
        fi
        read -rsp "Confirm password: " ADMIN_PASSWORD_CONFIRM
        echo ""
        if [[ "$ADMIN_PASSWORD" != "$ADMIN_PASSWORD_CONFIRM" ]]; then
            log_error "Passwords do not match"
            exit 1
        fi
    fi
}

# ─────────────────────────────────────────────────────────────────────────────
# CREATE ADMIN USER AFTER DEPLOYMENT
# ─────────────────────────────────────────────────────────────────────────────

create_admin_user() {
    local api_base="$1"
    
    log_step "Creating admin user: $ADMIN_EMAIL"
    
    # Wait for API to be ready
    for i in {1..30}; do
        if curl -kfs "${api_base}/api/health" >/dev/null 2>&1; then
            break
        fi
        sleep 2
    done
    
    # Create admin user via API
    local response
    response=$(curl -kfs -X POST "${api_base}/api/auth/users" \
        -H "Content-Type: application/json" \
        -d "{\"username\":\"admin\",\"email\":\"${ADMIN_EMAIL}\",\"full_name\":\"System Administrator\",\"role\":\"admin\",\"password\":\"${ADMIN_PASSWORD}\",\"is_active\":true,\"is_verified\":true}" 2>/dev/null || echo "failed")
    
    if echo "$response" | grep -q '"id"'; then
        log_info "✓ Admin user created successfully"
        echo "  Email: $ADMIN_EMAIL"
        echo "  Role: admin (full access)"
    elif echo "$response" | grep -q "already exists"; then
        log_warn "Admin user already exists, skipping creation"
    else
        log_warn "Could not auto-create admin user. Create manually after login:"
        echo "  curl -X POST ${api_base}/api/auth/users \\"
        echo "    -H \"Authorization: Bearer <token>\" \\"
        echo "    -d '{\"username\":\"admin\",\"email\":\"${ADMIN_EMAIL}\",\"full_name\":\"System Administrator\",\"role\":\"admin\",\"password\":\"${ADMIN_PASSWORD}\"}'"
    fi
}

# ─────────────────────────────────────────────────────────────────────────────
# DEPENDENCY CHECK
# ─────────────────────────────────────────────────────────────────────────────

check_deps() {
    log_info "Checking dependencies..."
    for cmd in docker docker-compose openssl curl; do
        if ! command -v "$cmd" &> /dev/null; then
            log_error "$cmd not found. Please install it first."
            exit 1
        fi
    done
    log_info "All dependencies found."
}

# ─────────────────────────────────────────────────────────────────────────────
# SECRETS GENERATION
# ─────────────────────────────────────────────────────────────────────────────

generate_secrets() {
    log_info "Generating secure secrets..."
    
    SECRET_KEY=$(openssl rand -base64 32)
    POSTGRES_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=')
    GRAFANA_PASSWORD=$(openssl rand -base64 16 | tr -d '/+=')
    JWT_SECRET=$(openssl rand -base64 32)
    
    cat > .env <<EOF
# MALINFO Production Environment - Auto-generated by deploy.sh
# DO NOT COMMIT THIS FILE - Store in secrets manager for production!

ENVIRONMENT=production
DEBUG=false

# Database
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
GRAFANA_PASSWORD=${GRAFANA_PASSWORD}
DATABASE_URL=postgresql+asyncpg://malinfo:\${POSTGRES_PASSWORD}@db:5432/malinfo
REDIS_URL=redis://redis:6379/0

# Secrets
SECRET_KEY=${SECRET_KEY}
JWT_SECRET_KEY=${JWT_SECRET}

# CORS - Configure for your domain
ALLOWED_ORIGINS=["https://${DOMAIN}"]

# VM Orchestrator
VM_ORCHESTRATOR_ENABLED=true
LIBVIRT_URI=qemu:///system

# ─────────────────────────────────────────────────────────────────────────────
# REQUIRED: Add your SMTP credentials for agency notifications
# ─────────────────────────────────────────────────────────────────────────────
# SMTP_HOST=smtp.gmail.com
# SMTP_PORT=587
# SMTP_USER=your-email@gmail.com
# SMTP_PASSWORD=your-16-char-app-password
# SMTP_TLS=true
# NOTIFICATION_FROM_EMAIL=noreply@${DOMAIN}
# AGENCY_NOTIFICATION_EMAIL=your-agency@gov.in

# ─────────────────────────────────────────────────────────────────────────────
# OPTIONAL: Threat Intelligence API Keys (enriches analysis)
# ─────────────────────────────────────────────────────────────────────────────
# VIRUSTOTAL_API_KEY=
# OTX_API_KEY=
# ABUSEIPDB_API_KEY=
# MISP_URL=
# MISP_API_KEY=
# MISP_VERIFY_SSL=true
EOF
    
    log_info "Generated .env with secure secrets."
    log_warn "EDIT .env to add SMTP credentials and threat intel API keys!"
}

# ─────────────────────────────────────────────────────────────────────────────
# SELF-HOSTED DEPLOYMENT (Full Control, KVM Support)
# ─────────────────────────────────────────────────────────────────────────────

deploy_selfhosted() {
    log_info "Deploying MALINFO (Self-Hosted) for domain: ${DOMAIN}"
    
    prompt_admin_credentials
    check_deps
    generate_secrets
    
    # Create storage directories
    log_info "Creating storage directories..."
    mkdir -p backend/storage/{uploads,reports,pcaps,vms,isos}
    mkdir -p backend/app/rules/yara/{sources,compiled,feeds,test_cases}
    mkdir -p deploy/certs
    
    # Generate self-signed cert for local testing (replace with Let's Encrypt for production)
    if [[ ! -f deploy/certs/fullchain.pem ]]; then
        log_info "Generating self-signed TLS certificate for ${DOMAIN}..."
        openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
            -keyout deploy/certs/privkey.pem \
            -out deploy/certs/fullchain.pem \
            -subj "/CN=${DOMAIN}" \
            -addext "subjectAltName=DNS:${DOMAIN},DNS:api.${DOMAIN}"
        log_warn "Using self-signed cert. Replace with Let's Encrypt for production!"
    fi
    
    # Build and start
    log_info "Building Docker images..."
    docker compose -f docker-compose.prod.yml build
    
    log_info "Starting services..."
    docker compose -f docker-compose.prod.yml --profile monitoring up -d
    
    # Wait for health check
    log_info "Waiting for services to be healthy..."
    for i in {1..60}; do
        if curl -kfs "https://localhost/api/health" >/dev/null 2>&1; then
            log_info "Backend is healthy!"
            break
        fi
        sleep 2
    done
    
    # Create admin user
    create_admin_user "https://localhost"
    
    # Print access info
    print_access_info "https://${DOMAIN}" "https://localhost"
}

# ─────────────────────────────────────────────────────────────────────────────
# FLY.IO DEPLOYMENT (Free Tier with KVM for VM Orchestrator)
# ─────────────────────────────────────────────────────────────────────────────

deploy_fly() {
    log_info "Deploying MALINFO to Fly.io for domain: ${DOMAIN}"
    
    prompt_admin_credentials
    
    if ! command -v fly &> /dev/null; then
        log_error "Fly CLI not found. Install: curl -L https://fly.io/install.sh | sh"
        exit 1
    fi
    
    fly auth login
    
    # Create postgres and redis
    log_info "Creating Fly PostgreSQL..."
    fly postgres create --name malinfo-db --region iad --initial-cluster-size 1 --yes || true
    
    log_info "Creating Fly Redis..."
    fly redis create --name malinfo-redis --region iad --yes || true
    
    # Get connection strings
    POSTGRES_URL=$(fly postgres connect -a malinfo-db -c "echo \$DATABASE_URL" 2>/dev/null | grep postgres || echo "")
    REDIS_URL=$(fly redis connect -a malinfo-redis -c "echo \$REDIS_URL" 2>/dev/null | grep redis || echo "")
    
    if [[ -z "$POSTGRES_URL" ]]; then
        log_warn "Could not auto-detect PostgreSQL URL. Check 'fly postgres connect -a malinfo-db'"
    fi
    
    log_info "Creating backend app..."
    fly apps create malinfo-api --org personal --yes 2>/dev/null || true
    
    log_info "Creating frontend app..."
    fly apps create malinfo-frontend --org personal --yes 2>/dev/null || true
    
    # Deploy backend with KVM
    log_info "Deploying backend (with KVM for VM orchestrator)..."
    cat > fly.backend.toml <<EOF
app = "malinfo-api"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile.prod"

[env]
  ENVIRONMENT = "production"
  DEBUG = "false"
  API_PREFIX = "/api"
  DATABASE_URL = "${POSTGRES_URL}"
  REDIS_URL = "${REDIS_URL}"
  VM_ORCHESTRATOR_ENABLED = "true"
  LIBVIRT_URI = "qemu:///system"
  ALLOWED_ORIGINS = '["https://${DOMAIN}", "https://malinfo-frontend.fly.dev"]'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  min_machines_running = 1

[mounts]
  source = "malinfo_storage"
  destination = "/app/storage"

[vm]
  memory = "4gb"
  cpus = 2
  enable_kvm = true

[processes]
  app = "gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --timeout 300"
EOF
    
    fly deploy --config fly.backend.toml --app malinfo-api
    
    # Create volume
    fly volumes create malinfo_storage --size 20 --app malinfo-api --yes || true
    
    # Deploy frontend
    log_info "Deploying frontend..."
    cat > fly.frontend.toml <<EOF
app = "malinfo-frontend"
primary_region = "iad"

[build]
  image = "nginx:1.27-alpine"

[http_service]
  internal_port = 8080
  force_https = true

[mounts]
  source = "frontend_dist"
  destination = "/usr/share/nginx/html"

[env]
  NGINX_CONFIG = """
  server {
      listen 8080;
      root /usr/share/nginx/html;
      index index.html;
      location / { try_files \$uri \$uri/ /index.html; }
      location /api/ { proxy_pass https://malinfo-api.fly.dev/api/; }
  }
  """
EOF
    
    fly deploy --config fly.frontend.toml --app malinfo-frontend
    
    # Custom domains
    log_info "Configuring custom domains..."
    fly certs create "${DOMAIN}" --app malinfo-frontend
    fly certs create "api.${DOMAIN}" --app malinfo-api
    
    # Wait for deployment and create admin
    log_info "Waiting for deployment to stabilize..."
    sleep 30
    create_admin_user "https://api.${DOMAIN}"
    
    log_info "Fly.io deployment complete!"
    print_access_info "https://${DOMAIN}" "https://api.${DOMAIN}"
}

# ─────────────────────────────────────────────────────────────────────────────
# RAILWAY DEPLOYMENT (Easiest, No KVM)
# ─────────────────────────────────────────────────────────────────────────────

deploy_railway() {
    log_info "Deploying MALINFO to Railway for domain: ${DOMAIN}"
    
    prompt_admin_credentials
    
    if ! command -v railway &> /dev/null; then
        log_error "Railway CLI not found. Install: npm install -g @railway/cli"
        exit 1
    fi
    
    create_frontend_dockerfile
    
    railway login
    railway init --name malinfo
    
    log_info "Adding PostgreSQL and Redis services..."
    railway add postgresql
    railway add redis
    
    log_info "Deploying backend..."
    railway service create backend --dockerfile backend/Dockerfile.prod
    
    log_info "Deploying frontend..."
    railway service create frontend --dockerfile deploy/Dockerfile.frontend
    
    log_warn "Configure environment variables in Railway dashboard!"
    log_warn "Set ALLOWED_ORIGINS=[\"https://${DOMAIN}\"]"
    log_warn "Add custom domain in Railway: ${DOMAIN}"
    log_warn "After deployment, run: create_admin_user manually via API"
}

# ─────────────────────────────────────────────────────────────────────────────
# HELPER FUNCTIONS
# ─────────────────────────────────────────────────────────────────────────────

create_frontend_dockerfile() {
    cat > deploy/Dockerfile.frontend <<'EOF'
FROM nginx:1.27-alpine
COPY nginx.frontend.conf /etc/nginx/conf.d/default.conf
COPY ../frontend /usr/share/nginx/html
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
EOF

    cat > deploy/nginx.frontend.conf <<'EOF'
server {
    listen 8080;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    
    location / {
        try_files $uri $uri/ /index.html;
    }
    
    location /api/ {
        proxy_pass https://malinfo-api.railway.internal/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
EOF
}

print_access_info() {
    local public_url="$1"
    local api_url="$2"
    
    echo ""
    echo "═══════════════════════════════════════════════════════════════"
    echo "  MALINFO DEPLOYMENT COMPLETE"
    echo "═══════════════════════════════════════════════════════════════"
    echo ""
    echo "  Public URL:     ${public_url}"
    echo "  API Health:     ${api_url}/api/health"
    echo "  Grafana:        ${public_url}:3000 (admin / check .env for GRAFANA_PASSWORD)"
    echo "  Prometheus:     ${public_url}:9090"
    echo ""
    echo "  Admin Account:"
    echo "    Email:    ${ADMIN_EMAIL}"
    echo "    Password: ${ADMIN_PASSWORD}"
    echo ""
    echo "  User Management (after login as admin):"
    echo "    1. Navigate to ${public_url}/#users"
    echo "    2. Click 'Create User' to add analysts, viewers, etc."
    echo "    3. Assign roles: admin | analyst | viewer"
    echo "    4. Enable MFA for each user (recommended)"
    echo ""
    echo "  Agency Notifications:"
    echo "    Edit .env and add SMTP credentials for CERT-In, Cyber Crime Cell alerts"
    echo ""
    echo "  Next Steps:"
    echo "    1. Point DNS ${DOMAIN} to this server's IP"
    echo "    2. Replace self-signed cert with Let's Encrypt:"
    echo "       make certs MODE=letsencrypt DOMAIN=${DOMAIN} EMAIL=admin@${DOMAIN}"
    echo "    3. Configure threat intel API keys in .env (VT, OTX, AbuseIPDB, MISP)"
    echo "    4. Review security checklist in DEPLOYMENT.md"
    echo "═══════════════════════════════════════════════════════════════"
}

# ─────────────────────────────────────────────────────────────────────────────
# MAIN ENTRY POINT
# ─────────────────────────────────────────────────────────────────────────────

main() {
    case "$PLATFORM" in
        selfhosted|local)
            deploy_selfhosted
            ;;
        fly|flyio)
            deploy_fly
            ;;
        railway)
            deploy_railway
            ;;
        render)
            log_error "Render deployment not automated. Use Render dashboard with DEPLOYMENT.md guide."
            exit 1
            ;;
        *)
            echo "Usage: $0 [selfhosted|fly|railway|render] [domain] [admin-email] [admin-password]"
            echo ""
            echo "Platforms:"
            echo "  selfhosted  - Deploy on your own VM (full control, KVM support for VM orchestrator)"
            echo "  fly         - Deploy to Fly.io (free tier, KVM support for VM orchestrator)"
            echo "  railway     - Deploy to Railway (easiest, free tier, NO KVM)"
            echo "  render      - Deploy to Render (manual via dashboard)"
            echo ""
            echo "Arguments:"
            echo "  domain         - Your domain (e.g., malinfo.myagency.gov)"
            echo "  admin-email    - Initial admin email (optional, will prompt)"
            echo "  admin-password - Initial admin password (optional, will prompt)"
            echo ""
            echo "Examples:"
            echo "  $0 selfhosted malinfo.myagency.gov admin@myagency.gov 'SecurePass123!'"
            echo "  $0 fly malinfo.myagency.gov"
            echo "  $0 railway malinfo.myagency.gov"
            exit 1
            ;;
    esac
}

main "$@"